# Generated by Django 5.0 on 2024-02-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_detail',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blog_detail',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='Uploads/Blog_Img'),
        ),
    ]
