# Generated by Django 5.0.1 on 2024-02-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_blog_detail_slug_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='back_img',
            field=models.ImageField(blank=True, null=True, upload_to='Uploads/Category_Img'),
        ),
    ]
