# Generated by Django 5.0.1 on 2024-03-07 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_alter_comments_blog_id_alter_reply_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_detail',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Blog', to='Blog.category'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='blog_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Blog.blog_detail'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relies', to='Blog.comments'),
        ),
    ]
